services:
  db:
    image: mysql:8.0
    container_name: mysql_whiTee
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1' $MYSQL_DATABASE"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

  app:
    build: .
    container_name: tomcat_whiTee
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
      - AES_KEY_BASE64=${AES_KEY_BASE64}

volumes:
  db_data:

